### ISSUE TITLE
Can we change last layer input from 32 to 64

### ISSUE THREAD

**Issue by jaideep11061982** [zhoudaxia233/EfficientUnet-PyTorch#3]
i see that in size dict for every b series model the last item size is 32 which is an input to the last node of Unet part of every efficient net model. Can we change 32 to 64 ?

**Comment by zhoudaxia233** [comment]
@jaideep11061982 Hello jaideep, it's been a long time since I worked on this project last time, so I forgot why I did that in the first place. You can download the source code and try to modify it. My guess is that it relates to the `concat_input` param (you should pay attention to this). It means whether you want to concatenate the original input image to the last few layers or not.
I hope this help. Feel free to post your results after experimenting :P
